---
name: Ross Dahlke
position: "Data Scientist and PhD Student"
address: "Stanford University"
www: rossdahlke.github.io
email: "ross.dahlke@stanford.edu"
twitter: ross_dahlke
github: rossdahlke
linkedin: rossdahlke
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 414141
output: 
  vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Education

```{r}
tribble(
  ~ degree, ~ year, ~ institution, ~ where, ~ details,
  "PhD: Communication", "2020-Present", "Stanford University", "Palo Alto, CA", "Knight-Hennessy Scholar (selected as 1 out of 75 incoming Stanford graduate students for 3-year full fellowship funding)",
  "PhD: Communication", "2020-Present", "Stanford University", "Palo Alto, CA", "Researcher in the Stanford Social Media Lab applying Natural Language Processing (NLP) and AI to study the connection between online behaviors and offline actions",
  "BA, Comprehensive Honors (Honors in the Liberal Arts and in the Major): Journalism and Political Science", "2014-2018", "University of Wisconsin-Madison", "Madison, WI", "Finalist for Rhodes and Marshall Scholarships",
  "BA, Comprehensive Honors (Honors in the Liberal Arts and in the Major): Journalism and Political Science", "2014-2018", "University of Wisconsin-Madison", "Madison, WI", "Recipient of Theodore Herfurth award for top undergraduate male"
) %>% 
  detailed_entries(degree, year, institution, where, details)
```

# Data Science & Consulting Experience

```{r}
tribble(
  ~ title, ~ year, ~ company, ~ where, ~ details,
  "Data Scientist", "2018-2020", "Ovative/ group", "Minneapolis, MN", "Full-stack data scientist using machine learning and computational techniques to optimize digital marketing budgets for clients such as UnitedHealthcare, Coach Bags, Calvin Klein, and Facebook Marketplace",
  "Data Scientist", "2018-2020", "Ovative/ group", "Minneapolis, MN", "Developed Bayesian machine learning algorithm for media mix modeling (MMM) to measure incremental return on ad spend (ROAS). Deployed model at scale as a part of a machine learning engineering pipeline",
  "Data Scientist", "2018-2020", "Ovative/ group", "Minneapolis, MN", "Set up A/B testing using power and precision calculations, measured test results",
  "Data Scientist", "2018-2020", "Ovative/ group", "Minneapolis, MN", "Worked with client teams to determine data science analyses for clients using methodologies including forecasting, clustering, Granger causality, and Markov Chains",
  "Political Data Consultant", "2015-Present", "Melissa Mulliken Consulting", "Madison, WI", "Build predictive models of voters for political campaigns using survey and voter contact data for state-wide, judicial, and municipal political campaigns using machine learning in R and Python. Models are used to allocate campaign budget, prioritize advertising audiences, and make strategic campaign decisions",
  "Political Data Consultant", "2015-Present", "Melissa Mulliken Consulting", "Madison, WI", "Analyze data using GIS and cartographic techniques including regression and clustering to help campaigns identify key geographic areas based on underlying demographic and electoral patterns",
  "Digital Intern", "2017-2018", "Lindsay, Stone & Briggs", "Madison, WI", "Developed social listening tools and pipelines to to discover how people are talking about brands and industried by using Natural Language Processing (NLP), network analysis, and deep learning (DL) for sentiment classification, topic modeling, influencer detection and image recognition"
) %>% 
  detailed_entries(company, year, title, where, details)
```

# Entrepreneurial Experience

```{r}
tribble(
  ~ title, ~ year, ~ company, ~ where, ~ details,
  "Founder & Entrepreneur", "2011-Present", "Ross Dahlke Cheese", "Westfield, WI", "Founded and manage cheese distribution business, partnering with a local family-owned cheese plant and grew sales from $3,000 in the first year to over $3M in total, employing 6 sales persons staffing up to 8 farmers markets and shows weekly"
) %>% 
  detailed_entries(company, year, title, where, details)
```

# Selected Presentations

```{r}
bibliography_entries("../bibliography/presentations.bib")
```





